LanType = "CN"
Checkbox_Enable = "开启 {0}"
Checkbox_AutoEnable = "自动"
Checkbox_Multi = "开启多角色模式"
DrawEnum_Language = "语言:"
EzTabBar_Retainers = "雇员"
EzTabBar_MultiMode = "多角色模式"
EzTabBar_Statistics = "Statistics"
EzTabBar_Settings = "设置"
EzTabBar_Beta = "Beta"
EzTabBar_About = "关于"
EzTabBar_Log = "Log"
EzTabBar_Debug = "Debug"
Retainers = "雇员"
Text_DataNotReady = "数据还没准备好"
Text_InventorySlots = "背包剩余空间"
Text_Ventures = "探险币:"
HelpMarker_Ventures = "插件将在探险币<2或背包剩余空间不足时被禁用"
TableSetupColumn_Name = "雇员名字"
TableSetupColumn_Venture = "探险剩余时间"
TableSetupColumn_Interaction = "操作倒计时"
Checkbox_RetainerName = "Retainer {0}"
ImGuiLineCentered_Timeouts = "AYSButtonClear Interaction Timeouts"
SmallButton_Timeouts = "Clear Interaction Timeouts"
TextWrapped_MultiMode = "多角色模式必须关闭Auto-afk"
TextWrapped_Please = "请在合理的范围内使用此功能，长时间保持它可能会引起不必要的注意。"
CollapsingHeader_SetupGuide = "使用指南"
TextWrapped_1 = "1. 登录每个角色，打开雇员菜单，勾选雇员"
TextWrapped_2 = "2. 给每个角色设置索引（每个服务器的第几个角色，此版本已按名字选角色，可以随意选择）"
TextWrapped_3 = "3. 确保你的角色在房区并靠近铃铛，建议在旅馆"
TextWrapped_4 = "4. 用完探险币或者背包满了会自动关闭当前角色。补充完探险币或者清理背包后需要重新启用"
TextWrapped_5 = "5. 可以设置一个首选角色，15分钟内没有任务会切换到改角色"