LanType = "EN"
Retainers = "Retainers"
Text_DataNotReady = "Data Not Ready"
Text_InventorySlots = "Inventory slots"
Text_Ventures = "Ventures:"
HelpMarker_Ventures = "The plugin will automatically disable itself at < 2 Ventures or inventory slots available."
TableSetupColumn_Name = "Name"
TableSetupColumn_Venture = "Venture"
TableSetupColumn_Interaction = "Interaction"
Checkbox_RetainerName = "Retainer {0}"
ImGuiLineCentered_Timeouts = "AYSButtonClear Interaction Timeouts"
SmallButton_Timeouts = "Clear Interaction Timeouts"